version: "3"
services:
  db:
    image: mysql:5.7.40-debian
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always
    ports:
      - '8701:3306'
    environment:
       MYSQL_DATABASE: 'test_db'
       MYSQL_ROOT_PASSWORD: 'root'
    networks:
        - connection
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8700:8000"
    volumes:
      - ./:/code/
    networks:
      - connection
    depends_on:
      - db

  phpmyadmin:
    depends_on:
      - db
    links:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8702:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - connection

networks:
  connection:

volumes:
  db-data:
