# Generated by Django 4.1.7 on 2023-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_origins_photo_origins_food_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origins',
            name='photo',
            field=models.ImageField(blank=True, default='img.jpg', upload_to='media/upload/origins/'),
        ),
    ]
